<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BankSeeder extends Seeder
{
	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run()
	{
		DB::table('banks')->insert([
			['code' => 1, 'name' => 'Banco do Brasil S.A.'],
			['code' => 3, 'name' => 'Banco da Amazônia S.A.'],
			['code' => 4, 'name' => 'Banco do Nordeste do Brasil S.A.'],
			['code' => 7, 'name' => 'Banco Nacional de Desenvolvimento Econômico e Social – BNDES'],
			['code' => 12, 'name' => 'Banco Inbursa S.A.'],
			['code' => 25, 'name' => 'Banco Alfa S.A.'],
			['code' => 29, 'name' => 'Banco Itaú Consignado S.A.'],
			['code' => 31, 'name' => 'Banco Beg S.A.'],
			['code' => 33, 'name' => 'Banco SANTANDER'],
			['code' => 37, 'name' => 'Banco do Estado do Pará S.A.'],
			['code' => 40, 'name' => 'Banco Cargill S.A.'],
			['code' => 41, 'name' => 'Banco do Estado do Rio Grande do Sul S.A.'],
			['code' => 47, 'name' => 'Banco do Estado de Sergipe S.A.'],
			['code' => 51, 'name' => 'Banco de Desenvolvimento do Espírito Santo S.A.'],
			['code' => 63, 'name' => 'Banco Bradescard S.A.'],
			['code' => 65, 'name' => 'Banco Andbank (Brasil) S.A.'],
			['code' => 66, 'name' => 'Banco Morgan Stanley S.A.'],
			['code' => 69, 'name' => 'Banco Crefisa S.A.'],
			['code' => 75, 'name' => 'Banco ABN AMRO S.A'],
			['code' => 76, 'name' => 'Banco KDB S.A.'],
			['code' => 77, 'name' => 'Banco Inter S.A.'],
			['code' => 80, 'name' => 'B&T Cc Ltda'],
			['code' => 83, 'name' => 'Banco da China Brasil S.A.'],
			['code' => 94, 'name' => 'Banco Finaxis S.A.'],
			['code' => 96, 'name' => 'Banco B3 S.A.'],
			['code' => 104, 'name' => 'Banco Caixa Econômica Federal'],
			['code' => 107, 'name' => 'Banco BOCOM BBM S.A.'],
			['code' => 117, 'name' => 'Advanced Cc Ltda'],
			['code' => 121, 'name' => 'Banco Agibank S.A.'],
			['code' => 122, 'name' => 'Banco Bradesco BERJ S.A.'],
			['code' => 172, 'name' => 'Albatross Ccv S.A'],
			['code' => 184, 'name' => 'Banco Itaú BBA S.A.'],
			['code' => 188, 'name' => 'Ativa Investimentos S.A'],
			['code' => 196, 'name' => 'Banco Fair Corretora de Câmbio S.A'],
			['code' => 197, 'name' => 'Stone Pagamentos'],
			['code' => 204, 'name' => 'Banco Bradesco Cartões S.A.'],
			['code' => 208, 'name' => 'Banco BTG Pactual S.A.'],
			['code' => 212, 'name' => 'Banco Original'],
			['code' => 213, 'name' => 'Banco Arbi S.A.'],
			['code' => 217, 'name' => 'Banco John Deere S.A.'],
			['code' => 218, 'name' => 'Banco BS2 S.A.'],
			['code' => 222, 'name' => 'Banco Credit Agricole Brasil S.A.'],
			['code' => 224, 'name' => 'Banco Fibra S.A.'],
			['code' => 233, 'name' => 'Banco Cifra S.A.'],
			['code' => 237, 'name' => 'Banco Bradesco S.A.'],
			['code' => 241, 'name' => 'Banco Clássico S.A.'],
			['code' => 243, 'name' => 'Banco Máxima S.A.'],
			['code' => 246, 'name' => 'Banco ABC Brasil S.A.'],
			['code' => 249, 'name' => 'Banco Investcred Unibanco S.A.'],
			['code' => 260, 'name' => 'Nubank'],
			['code' => 265, 'name' => 'Banco Fator S.A.'],
			['code' => 266, 'name' => 'Banco Cédula S.A.'],
			['code' => 280, 'name' => 'Banco Willbank'],
			['code' => 290, 'name' => 'PagBank'],
			['code' => 300, 'name' => 'Banco de La Nacion Argentina'],
			['code' => 318, 'name' => 'Banco BMG S.A.'],
			['code' => 323, 'name' => 'Mercado Pago'],
			['code' => 335, 'name' => 'Banco Digio S.A'],
			['code' => 336, 'name' => 'Banco C6 S.A – C6 Bank'],
			['code' => 340, 'name' => 'Superdigital'],
			['code' => 341, 'name' => 'Banco Itau'],
			['code' => 368, 'name' => 'Banco Carrefour'],
			['code' => 370, 'name' => 'Banco Mizuho do Brasil S.A.'],
			['code' => 376, 'name' => 'Banco J. P. Morgan S.A.'],
			['code' => 380, 'name' => 'PicPay'],
			['code' => 389, 'name' => 'Banco Mercantil do Brasil S.A.'],
			['code' => 394, 'name' => 'Banco Bradesco Financiamentos S.A.'],
			['code' => 412, 'name' => 'Banco Capital S.A.'],
			['code' => 422, 'name' => 'Banco Safra'],
			['code' => 456, 'name' => 'Banco MUFG Brasil S.A.'],
			['code' => 473, 'name' => 'Banco Caixa Geral – Brasil S.A.'],
			['code' => 479, 'name' => 'Banco ItauBank S.A'],
			['code' => 494, 'name' => 'Banco de La Republica Oriental del Uruguay'],
			['code' => 495, 'name' => 'Banco de La Provincia de Buenos Aires'],
			['code' => 505, 'name' => 'Banco Credit Suisse (Brasil) S.A.'],
			['code' => 600, 'name' => 'Banco Luso Brasileiro S.A.'],
			['code' => 604, 'name' => 'Banco Industrial do Brasil S.A.'],
			['code' => 612, 'name' => 'Banco Guanabara S.A.'],
			['code' => 626, 'name' => 'Banco Ficsa S.A.'],
			['code' => 641, 'name' => 'Banco Alvorada S.A.'],
			['code' => 653, 'name' => 'Banco Indusval S.A.'],
			['code' => 654, 'name' => 'Banco A.J.Renner S.A.'],
			['code' => 707, 'name' => 'Banco Daycoval S.A.'],
			['code' => 720, 'name' => 'Banco Maxinvest S.A.'],
			['code' => 735, 'name' => 'Neon Pagamentos'],
			['code' => 739, 'name' => 'Banco Cetelem S.A.'],
			['code' => 745, 'name' => 'Banco Citibank S.A.'],
			['code' => 746, 'name' => 'Banco Modal S.A.'],
			['code' => 748, 'name' => 'Banco Cooperativo Sicredi S.A.'],
			['code' => 752, 'name' => 'Banco BNP Paribas Brasil S.A.'],
			['code' => 756, 'name' => 'Banco Cooperativo do Brasil S.A. – BANCOOB'],
			['code' => 757, 'name' => 'Banco KEB HANA do Brasil S.A.'],
		]);
	}
}